INSERT INTO manufacturers (man_code,man_desc) VALUES
 ('BUF','Buffalo Games'),
 ('CEL','Celtic Puzzles'),
 ('CHA','Chad Valley'),
 ('CIT','Citadel Puzzles'),
 ('CLE','Clementoni'),
 ('DIN','Dino'),
 ('EDU','Educa Jigsaws'),
 ('ESC','Escher Jigsaws'),
 ('FAL','Falcon Puzzles'),
 ('FSC','Fx Schmidt'),
 ('GIB','Gibsons Puzzles'),
 ('HAM','James Hamilton'),
 ('HAS','Hasbro'),
 ('HEY','Heye Puzzles'),
 ('JIG','Jigthings'),
 ('JRJ','JR Jigsaw Puzzles'),
 ('JUM','Jumbo Jigsaws'),
 ('KIN','King International'),
 ('LAR','Larsen Tray Puzzles'),
 ('LUX','Classic DeLuxe'),
 ('MAS','MasterPieces'),
 ('MEL','Melissa and Doug'),
 ('OTT','Otter House Jigsaws'),
 ('PAU','Paul Lamond'),
 ('PRE','Susan Prescot'),
 ('RAV','Ravensburger'),
 ('SCH','Schmidt'),
 ('SER','Serendipity'),
 ('SUN','SunsOut Puzzles'),
 ('TAI','Tailten Games'),
 ('TDC','TDCGames'),
 ('TOY','D-Toy Jigsaws'),
 ('WAD','Waddingtons'),
 ('WAS','Wasgij Puzzles'),
 ('WHI','White Mountain Puzzles');